"""Report Writing Agent — cloud-neutral agent logic (generated by new-agent; ADR-0004).

This package imports ONLY ``core`` abstractions — never a cloud SDK, never a vendor model
name. Enforced in CI by ``core.checks.no_cloud_sdk`` (scoped to ``agents/*/agent/``).
"""
